/**
 * =============================================================================
 * MyNaati Backend — MFA (TOTP) Utility
 * =============================================================================
 * 
 * Provides TOTP (Time-Based One-Time Password) functions for multi-factor
 * authentication using the `otplib` library.
 * 
 * Compatible with Google Authenticator, Authy, Microsoft Authenticator, etc.
 * 
 * Flow:
 *   1. User enables MFA → generateSecret() → store secret in DB
 *   2. Generate QR code → generateQrCodeUrl() → display to user
 *   3. User scans QR → enters 6-digit code → verifyToken() → MFA enabled
 *   4. On login → user enters 6-digit code → verifyToken() → access granted
 */

const { authenticator } = require('otplib');
const QRCode = require('qrcode');

// Allow ±2 time steps (±60 seconds) for clock drift
authenticator.options = { window: 2 };

/**
 * Generate a new TOTP secret key for a user.
 * This secret should be stored securely in the database.
 * 
 * @returns {string} Base32-encoded secret key
 */
function generateSecret() {
    return authenticator.generateSecret();
}

/**
 * Generate a QR code data URL for the user to scan with their authenticator app.
 * 
 * @param {string} email - The user's email address (used as account label)
 * @param {string} secret - The TOTP secret key generated by generateSecret()
 * @returns {Promise<string>} Base64-encoded PNG image data URL
 */
async function generateQrCodeUrl(email, secret) {
    const appName = process.env.MFA_APP_NAME || 'MyNaati';
    const otpAuthUrl = authenticator.keyuri(email, appName, secret);
    return QRCode.toDataURL(otpAuthUrl);
}

/**
 * Verify a TOTP token entered by the user against their stored secret.
 * Tokens are valid for a 30-second window (±1 step by default).
 * 
 * @param {string} token - The 6-digit code entered by the user
 * @param {string} secret - The user's stored TOTP secret key
 * @returns {boolean} True if the token is valid for the current time window
 */
function verifyToken(token, secret) {
    return authenticator.verify({ token, secret });
}

module.exports = {
    generateSecret,
    generateQrCodeUrl,
    verifyToken,
};
